### ISSUE TITLE
[BUG?] Can not upload file without YAML header

### ISSUE THREAD

**Issue by Dobrokhotov1989** [ClaudioZandonella/trackdown#22]
Hi,

I have a problem uploading a child Rmd file that does not contain YAML header. Specifically `upload_file()` returns error "Error: There are some issues in the identification of YAML start/end line indexes" when `hide_code = TRUE`.  Upload works just fine if  `hide_code = FALSE` or with empty YAML header.

I'm not sure whether it is a really bug or it's kinda "safety feature" that you need to preserve.

**Comment by ClaudioZandonella** [comment]
Hi @Dobrokhotov1989!

Thanks for reporting this problem. I would say it is a "Black Swan Fallacy". When developing the code I thought "All Rmd documents have a YAML header" but I was wrong, child Rmd flies exist😅... 

Actually, there are no safety reasons behind this so I will make the required changes to allow uploading documents without YAML header as well. I need only to do some checks. In a few days, I will update everything!

Thanks again!

**Comment by ClaudioZandonella** [comment]
Hi @Dobrokhotov1989,

sorry for the long time it took me to fix this. Now child files are supported and the argument `hide_code = TRUE` can be used regardless of whether the file contains header code and/or chunks or not. So everything should be fine. 

Changes are in the new version of the package (v 1.1.0). The new version is still in the `develop` branch (I could not yet merge changes in the `master` branch due to some issues in the Github actions).  You can install it by,

`remotes::install_github("ClaudioZandonella/trackdown", ref = "develop")`

Shortly I will marge changes in the `master` branch and upgrade the CRAN version as well.

Again thank you for helping to improve the package!❤️
