### ISSUE TITLE
Error with download_file when there are no code chunks

### ISSUE THREAD

**Issue by weiyangtham** [ClaudioZandonella/trackdown#24]
I get the following error message when I *upload then download* a file with no code chunks at all. 

`Error in seq_len(nrow(chunk_info)) :    argument must be coercible to non-negative integer`

I attached a simple R Markdown example as a .txt file.
[trackdown.txt](https://github.com/ClaudioZandonella/trackdown/files/7637554/trackdown.txt)
Even just adding a completely empty chunk without a label seems to solve the problem.

This doesn't seem to be a problem if you upload a .rmd file that has code chunks then delete the chunk labels in the Google Doc.

**Comment by ClaudioZandonella** [comment]
Hi @weiyangtham,

thank you for reporting this issue. We fixed the problem and now the argument `hide_code = TRUE` can be used regardless of whether the file contains header code and/or chunks or not. So everything should be fine. 

Changes are in the new version of the package (v 1.1.0). The new version is still in the `develop` branch (I could not yet merge changes in the `master` branch due to some issues in the Github actions).  You can install it by,

`remotes::install_github("ClaudioZandonella/trackdown", ref = "develop")`

Shortly I will marge changes in the `master` branch and upgrade the CRAN version as well.

Again thank you for helping to improve the package!❤️

**Comment by weiyangtham** [comment]
Thanks for the quick response and great work!
