### ISSUE TITLE
Google denies access (current GitHub version)

### ISSUE THREAD

**Issue by MeikeSteinhilber** [ClaudioZandonella/trackdown#37]
I tried the CRAN version and everything works as expected. (Its a wonderful package sofar, thanks!!!)
But when I upgrade to your current master version on GitHub, using:

`remotes::install_github("claudiozandonella/trackdown", build_vignettes = TRUE)`

I cannot use trackdown functions anymore like:
```
 path <- "1_paper/1_paper.Rmd"
upload_file(file = path, hide_code = TRUE)
update_file(file = path, hide_code = TRUE)
download_file(file = path)
```
I get in R the following error: 

> Error in curl::curl_fetch_memory(url, handle = handle) : 
> Could not resolve host: metadata.google.internal

and from Goofle I get this message: 

> This app is blocked
> This app has attempted to access sensitive data in your Google Account. To protect your account, we have blocked access.

![grafik](https://user-images.githubusercontent.com/78479286/204555950-db7327ed-2cef-4824-818a-76a2b9cbbb37.png)

Could you give more details how to solve this problem (maybe even add it to the vignette)? Because the changes on the master branch are really great and I would love to use them!!! ♥

**Comment by ClaudioZandonella** [comment]
Dear @MeikeSteinhilber,

thanks for pointing out this issue.

The current developmental version available in GitHub uses its own Google API credentials (OAuth client ID and secret). 
Unfortunately, google offers limited access (100 users) to apps under development and we recently reached this limit.

<img width="590" alt="Screenshot 2022-11-29 at 15 46 27" src="https://user-images.githubusercontent.com/44664104/204560287-4eae18bf-1f67-4c71-b1df-6d45cfdf4c24.png">

To get unlimited access I need to complete all the verification steps required by Google. Unfortunately, the process is slow and I was rejected several times. The reason is that `trackdown` is an r-package working with in-line commands but they require GUI interfaces with logos etc. to pass all the verification steps. 

At the moment I am a little bit stuck on this problem. An Idea is to create a Shiny App to allow Google verification (but I am not sure it will be enough for Google). An alternative is to create a different authentication process where users create their own  API credentials (something simial to what {gmailr} package does https://gmailr.r-lib.org/ ).

I am sorry I was not able to fix this sooner, but in the past months, I changed my job and city. Unfortunately, I was not able to find enough time to work on this issue. I really hope to get back to it as soon as possible.

As a temporary solution, you could try to create your own API credentials and use them. Some documentation is provided here:

- https://gargle.r-lib.org/articles/get-api-credentials.html 
- https://gmailr.r-lib.org/
- https://gargle.r-lib.org/articles/gargle-auth-in-client-package.html
- https://googledrive.tidyverse.org/articles/bring-your-own-app.html

This are the functions used by trackdown to activate credentials
- https://github.com/ClaudioZandonella/trackdown/blob/master/R/trackdown_auth.R

This are the required scopes needed by trackdown

<img width="646" alt="Screenshot 2022-11-29 at 15 54 48" src="https://user-images.githubusercontent.com/44664104/204562433-5029a046-2806-4a45-ab50-c57f9ad512e3.png">

I am sorry if this seems confusing, I will find out the time to document this process a little bit better in the next weekends

**Comment by MeikeSteinhilber** [comment]
Thanks for the fast response! 👍 I will try it again with your described help!

**Comment by ClaudioZandonella** [comment]
hi @MeikeSteinhilber,

I just released a new version of trakdown that allow using custom app credentials. Unfortunately, it is necessary that users create their own app. I added a detailed guide here https://claudiozandonella.github.io/trackdown/articles/oauth-app-configuration.html

let me know if now it is possible to use trackdown or if more details are needed.

Hopefully in the future we will be able to pass google authentication process
