### ISSUE TITLE
OAuth App Config. new msg from google

### ISSUE THREAD

**Issue by DylanMG** [ClaudioZandonella/trackdown#55]
Just found trackdown and it looks like a great package to solve some issues I'm facing for collaborating with non-programmers. I went to get started by following the [OAuth config guidelines](https://claudiozandonella.github.io/trackdown/articles/oauth-app-configuration.html) but noticed something new at step 8 when I went to push to produciton:
![image](https://user-images.githubusercontent.com/37416118/215606271-90b5835b-4afb-4c99-b4b9-637770d2ed6f.png)
Do I worry about this message? I am not interested in sharing all of that info with Google just to make collaboration with others more easy. 
Further, during step 5, there was no pop-up window. I wonder if these issues are connected and something going on at google? 

Thanks for any help.

**Comment by ClaudioZandonella** [comment]
Daer @DylanMG,

Thanks for using trackdown ❤️

You are right! I went through the OAuth configuration again and Google slightly changed the messages:

- At Step 5 there is no longer the pop-up window regarding the sensitive scopes
- At Step 8 the message is changed

You should not worry about this message. It is just reporting the requirements for the verification of your app by Google.

We created the app and published it so other users can use it. As our newly created app uses sensitive scopes (it uses the google docs API to upload/download files on users google drive), Google allows only a limited number of users (100). To be open o anyone, the app must be verified by Google. This requires all the points listed in the message. However, this is an extra step you do not need.

If you are planning to use your new app with a limited number of users (less than 100). You do not need this verification. So you do not need to share other information with Google (or at least no more information than what Google is already collecting on each of us😅).

Please let me know if now the procedure is clear. This would help me to improve the documentation! 

I will update the instructions on the documentatio👍

**Comment by DylanMG** [comment]
Hi @ClaudioZandonella thanks for getting back to me so soon! 

This mostly makes sense. When updating the documentation, can you make the language around "the app" and "your new app" more clear? This is my first time working with a google API and I suspect I'm not the only user in this boat. 

When we use trackdown to write/read/update a google doc, are we functionally making an app? This is what isn't clear to me. I may have over 100 but not sure of the scale of this yet. I would be using it for some government work so understanding these permissions is important.

**Comment by ClaudioZandonella** [comment]
Hi @DylanMG 

Sorry for the late reply.

You are right the use of the term "app" is not really clear. Working with a google API,  'app' should be considered as a service. We use Google API to make some actions (e.g., upload/ download file from google drive), but to use google API we need to register our service. This is because there are some rate limits for the use of API and some specific APIs are not free (for example google maps API).

Google calls this 'app' because in most cases our service would be embedded in a proper web/mobile app, but in our case, everything is done in R. So we do not have a real application but the R code send requests using our service credentials to use the google API. 

Hope this is now more clear.

Regarding  your specific use:

> I may have over 100 but not sure of the scale of this yet. 

The limit of 100 regards the number of people using trackdown with your app/service and not the number of colleagues on google drive. If you are the only one using trackdown whereas you colleagues write/make review on google drive, the count is 1.

Of course if you have more than 100 colleagues using R and using `trackdown` you could create multiple services/app.

Note that the service registration is different from the part related to your Google user authentication. Multiple google users can use the same service (in this case up to 100).

> I would be using it for some government work so understanding these permissions is important.

This is quite important. Here are some points:

- When creating your service/app you select the `scopes`, this is what your service/app can do, that is mainly which google APIs can be used.
- The service/app is used by trackdown to upload/download files in the user's google drive. However, your service/app is not linked to your personal google drive. Every user needs to authenticate with their own google profile and will have access only to their google drive. 
- Thus, If you share your service/app with other users they can not see your google drive. 

So summarizing. After you authenticate with your google account, trackdown has access to your google drive (you and only you). This is required to upload/download files.

Anyway, my suggestion could be to create another google account and use that one for the trackdown collaboration.  So you are 100% sure to keep everything separate.

Let me know if you need more information. In case (if you need a call or whatever), you can contact me at claudiozandonella@gmail.com

**Comment by ClaudioZandonella** [comment]
Documentation is now updated!
